version: '3'
services:
    app:
      container_name: aps-final
      restart: always
      build: .
      ports:
        - '3000:3000'
      environment:
        - NODE_ENV=production
        - MONGODB_HOST_NAME=mongo
        - MONGODB_PORT=27017
        - MONGODB_NAME=school
        - EMAIL=apseduinfo@gmail.com
        - PASSWORD=surya001
        - ADMIN_EMAIL=apsedugroup@gmail.com
        - KEY_SECRET=FajkD3TQukf0LtuEBY5GQu2e
        - KEY_ID=rzp_test_BZqDgya0lyTLd0
        - SENDGRID=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
        - URL=http://arrowachievers.com
      volumes:
        - ../apsImageData:/apsEducation/images
      depends_on:
        - mongo
    mongo:
      image: mongo:4.0.12-xenial
      restart: always
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_DATABASE=school
      volumes:
        - ../apsEducationData:/data/db